export default [
    {
      "name": "Liceo Augusto dHalamr",
      "Comuna": "Ñuñoa",
      "id": "100",
      "Direccion": "Ramón Cruz 589",
      "Telefono": "+5623793123",
      "Email": "contacto@liceoaugustodhalmar.cl",
      "puntuación": "200",
      "Reseña": "Institución educacional de enseñanza media Científico – Humanista perteneciente a la corporación municipal de desarrollo social de Ñuñoa, que ofrece a sus alumnos potenciar el desarrollo de sus capacidades a través de un compromiso integral protagónico, que los habilite para desempeñarse diversificadamente en el económico productivo de servicio, en sus niveles Medio y Superior.",
      "web": "http://www.liceoaugustodhalmar.cl",
      "colegioStudent": true,
      "escuelaStaff": false,
      "alive": true,
      "image": "https://otdchile.org/wp-content/uploads/2019/08/liceo-augusto.jpg",
    },
 {
   "name": "Liceo Bicentenario San Pedro",
   "Comuna": "Puente Alto",
   "id": "101",
   "Direccion": "Claudio Matte 179",
   "Telefono": "+56 227 975 296",
   "Email": "lorena.contreras@cmpuentealto.cl",
   "puntuación": "200",
   "Reseña":"Buscamos ser una Corporación Municipal que propicia oportunidades de desarrollo integral a la comunidad de Puente Alto, con equipos de trabajo motivados y comprometidos, que entregan servicios con cariño y eficiencia en Educación, Salud y Atención de Menores.Ser referentes en otorgar un servicio público oportuno, capaz de satisfacer las necesidades de las personas en Educación, Salud y Atención de Menores, mejorando la calidad de vida de la comunidad puentealtina.",
   "web": "http://www.colegioakros.cl/",
   "colegioStudent": true,
   "escuelaStaff": false,
   "alive": true,
   "image" :"https://liceosanpedro.cl/wp-content/uploads/2016/02/cesfam.jpg",

  },
 {
   "name": "Intituto Nacional ",
   "Comuna": "Santiago",
   "id": "102",
   "Direccion": "Arturo Prat 33",
   "Telefono": "+5626964294",
   "Email": "rectoria@institutonacional.cl",
   "puntuación": "200",
   "Reseña": "Instituto Nacional es la de formar personas integrales (competentes) intelectualmente y orientadas a la excelencia académica con habilidades sociales emocionales valóricas y ecológicas, para no solo integrarse a la sociedad, sino para transformarla. La finalidad educativa del Instituto Nacional es formar ciudadanos. Formar ciudadanos implica educar para la vida,es decir: educar para el saber, para el amor, para el trabajo, educar personas amantes del derecho y la verdad. Significa asumir a la persona en desarrollo como ser perfectible, dialogante y solidaria. Como lo plantea el postulado de Camilo Henríquez El gran fin del Instituto es dar a la patria ciudadanos que la dirijan, la defiendan, la hagan florecer y de le den honor",
   "web": "https://institutonacional.cl/",
   "colegioStudent": true,
   "escuelaStaff": false,
   "alive": true,
   "image" :"https://live.staticflickr.com/2725/4424054643_3823cd0db0_b.jpg",

},
 { 
   "name": "Liceo Carmela Carvajal de Prat",
   "Comuna": "Providencia",
   "id": "103",
   "Direccion": "Av. Italia 980, PROVIDENCIA",
   "Telefono": "+562 320 36 850",
   "Email": "secretaria@liceocarmelacarvajal.cl",
   "puntuación": "200",
   "Reseña": "Queremos ser una comunidad educativa con una identidad que perdure y donde, efectivamente, se destaca la persona como centro fundamental del quehacer cotidiano, vivenciando los valores de una sociedad humanista, democrática, progresista y con visión de futuro. Queremos realizar actividades destinadas a desarrollar armónicamente lo físico, lo valórico, lo afectivo y lo intelectual, con el objetivo de propiciar la superación personal y mantener la excelencia académica. Queremos ser una comunidad eficiente, creativa, responsable, tolerante, honesta, solidaria, leal, feliz, ayudando a formar nuevas generaciones de mujeres conscientes, conocedoras, autodisciplinadas y comprometidas en una sociedad dinámica, diversa y globalizada. Queremos trabajar coordinadamente con organismos sociales y educativos para fortalecer nuestro quehacer.",
   "web": "https://www.liceocarmelacarvajal.cl/",
   "colegioStudent": true,
   "escuelaStaff": false,
   "alive": true,
   "image" :"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxmurZvl14hZibWSErZ5fPn11ukYaoAjM9ecxDkfDPOx3G9Q72Wg&s",

},
{
   "name": "Liceo Nacional de Maipú",
   "Comuna": "Maipú",
   "id": "104",
   "Direccion": "Av. Portales 2471",
   "Telefono": "+562585 2308",
   "Email": "No Registra",
   "puntuación": "200",
   "Reseña": "Liceo Nacional de Maipú, es de naturaleza humanista, científica y laica. Promueve el respeto de la dignidad y valores del ser humano, como cimiento para la formación integral del alumno, estimulando el desarrollo de sus capacidades intelectuales, afectivas, espirituales y psicomotrices; Valora su historia y su cultura, nuestro medio ambiente las prácticas democráticas, la tolerancia, el pluralismo y la sana convivencia en el marco de la Jornada Escolar Completa Diurna. Promueve el mejoramiento continuo de la institución y la comunidad en general. Desarrollar una formación integral, basada en capacidades, destrezas, conocimientos y habilidades que apuntan a la excelencia académica para ingresar a la Universidad.",
   "web": "http://www.liceonacionaldemaipu.cl/",
   "colegioStudent": true,
   "escuelaStaff": false,
   "alive": true,
   "image" :"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQGYT_Y9cdNF0f2kRDCbRUZY576Wug1VgbpTo5MoGaM9j9D7QOMCQ&s",

},
{
   "name": "Liceo Amanda Labarca",
   "Comuna": "Vitacura",
   "id": "105",
   "Direccion": "Av. Padre Hurtado Norte 1150",
   "Telefono": "+562212 9494",
   "Email": "info@amandalabarca.cl ",
   "puntuación": "200",
   "Reseña": "El Liceo municipalizado Amanda Labarca privilegiará el respeto, la responsabilidad y el amor a la verdad en un trabajo interactivo entre los actores de la comunidad educativa. Tenderá así mismo al desarrollo integral del alumno posibilitando el empleo de todas sus capacidades y potencialidades con el propósito de formar estudiantes comprometidos con su proceso de aprendizaje y con su entorno para desenvolverse en un mundo globalizado. El colegio en consecuencia, será un lugar de encuentro y acogida donde la comunidad educativa recibirá el apoyo requerido para su desarrollo y podrán relacionarse en un ambiente de confianza y colaboración mutua",
   "web": "http://www.amandalabarca.cl/",
   "colegioStudent": true,
   "escuelaStaff": false,
   "alive": true,
   "image" :"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWY2lHU0ppnXMP34ilLJgIFtfMpdxhX3jYKXmvVlc1kBuFGaG-&s",

},
{
   "name": "Colegio ciudad de Frankfort",
   "Comuna": "San Joaquin",
   "id": "106",
   "Direccion": "Francisca de Rimini 3464",
   "Telefono": "+5622553 9797",
   "Email": "eciudaddefrankfort@gmail.com",
   "puntuación": "200",
   "Reseña": "En la tarea de educar, esta unidad educativa cuya vocación es la formación de niños y niñas en un lugar afectivo en que sus intereses y necesidades sean satisfechos, la escuela se enmarca en la visión de educar con afectividad, es por eso que sus profesionales forman un equipo cohesionado, altamente comprometido, capacitado académicamente y con altas expectativas de sus alumnos.",
   "web": "https://sanjoaquineduca.cl/index.php/pagina-ejemplo/escuela-basica-ciudad-de-frankfort/",
   "colegioStudent": true,
   "escuelaStaff": false,
   "alive": true,
   "image" :""

},
{
  "name": "Colegio Pan American College",
  "Comuna": "San Miguel",
  "id": "107",
  "Direccion": "Llano Subercaseaux #3653",
  "Telefono": "+562555 0552",
  "Email": "secretaria@panamerican.cl",
  "puntuación": "200",
  "Reseña": "Nuestra comunidad educacional se impone como misión el trabajo solidario de la unidad educativa, para proporcionar los recursos materiales necesarios para proponer los objetivos pedagógicos atrayentes, para incentivar actividades que permitan alcanzar los ideales señalados en la visión de nuestro proyecto.",
  "web": "https://www.panamerican.cl/",
  "colegioStudent": true,
  "escuelaStaff": false,
  "alive": true,
  "image" :""

},
{
  "name": "Instituto Cumbres de Cóndores Oriente",
  "Comuna": "Renca",
  "id": "108",
  "Direccion": "Senador Jaime Guzmán 1365",
  "Telefono": "+5622646 3163",
  "Email": "institutocondoresoriente@edurenca.cl",
  "puntuación": "200",
  "Reseña": "Enfocados en formar ciudadanos y personas integrales, el Instituto Cumbre de Cóndores Oriente (ICCO) es uno de los tres liceos de nuestra comuna. Acogemos a estudiantes de educación media para su preparación técnico profesional y universitaria en la educación superior. Somos un liceo de excelencia académica que fomenta la visión de futuro de sus estudiantes y dar respuesta a los desafíos del mundo de hoy, comprometidos con su comunidad y responsables de su entorno. Contamos con especialidades técnicas de enfermería, telecomunicaciones y científico-humanista.",
  "web": "https://www.renca.cl/instituto-cumbre-de-condores-oriente/",
  "colegioStudent": true,
  "escuelaStaff": false,
  "alive": true,
  "image" :"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpkzk-RRzH2oC1lqnMRUgGuVq4DG_Qp8S2N35a7hilZU9hot4QzQ&s"

},
{
  "name": "Colegio Elvira Hurtado de Matte",
  "Comuna": "Quinta Normal",
  "id": "109",
  "Direccion": "Av. Carrascal 4503",
  "Telefono": "2707 5877",
  "Email": "No Registra",
  "puntuación": "200",
  "Reseña": "La Sociedad de Instrucción Primaria, hoy SIP Red de Colegios, es una de las más antiguas corporaciones educacionales de derecho privado del país. Su objetivo es brindar educación de excelencia a niños y jóvenes, haciendo realidad el derecho a la igualdad de oportunidades que debe existir en toda sociedad. El presente Proyecto Educativo se mantiene fiel a lo señalado en 1856 por Benjamín Vicuña Mackenna, uno de sus fundadores, al afirmar que el programa y fin de la institución será siempre “la acción, el ejemplo y las obras”. ",
  "web": "http://www.elvirahurtado.cl/",
  "colegioStudent": true,
  "escuelaStaff": false,
  "alive": true,
  "image" :"http://www.rosaelviramatte.cl/wp-content/uploads/2015/11/mrg-37-de-75-350x240.jpg"

},
{
  "name": "Colegio Santiago Quilicura",
  "Comuna": "Quilicura",
  "id": "110",
  "Direccion": "AV. LAS TORRES 0946",
  "Telefono": "+5622627 2821",
  "Email": "No Registra",
  "puntuación": "200",
  "Reseña": "Lograr educación preescolar y escolar de calidad que maximice las oportunidades de aprender, en un contexto valórico cristiano.",
  "web": "http://www.redcrecemos.cl/prontus_red/site/edic/base/port/inicio_quilicura.html",
  "colegioStudent": true,
  "escuelaStaff": false,
  "alive": true,
  "image" :"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTN_v2erjJRrSFjVJZx9lGLaECZvMAcsO0B66ZqAAIa7j4htbI-RA&s"

},
{
  "name": "Colegio San Felipe",
  "Comuna": "Pudahuel",
  "id": "111",
  "Direccion": "Av. Laguna Sur 7241",
  "Telefono": "+5623275 3100",
  "Email": "direccion24966@gmail.com",
  "puntuación": "200",
  "Reseña": "Educar niños y jóvenes, en un ambiente fraterno, solidario e inclusivo, abierto a la comunidad, entregando valores y condiciones, como el respeto, compañerismo y autocuidado, fortaleciendo los aprendizajes significativos y aceptando las normas de un sistema democrático, centrado principalmente en la estrecha relación,entre familia y el colegio, con el fin de potenciar su formación e integración en una sociedad cada vez más competitiva, respetando el entorno y nuestra identidad nacional.",
  "web": "https://www.colegiosanfelipe.cl/",
  "colegioStudent": true,
  "escuelaStaff": false,
  "alive": true,
  "image" :"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnys9ztwTvcnbdIp-LO98B2mwoCD_qaoKKmkBJwX4w9qu5ue0rFA&s"

},
{
  "name": "Colegio Likankura",
  "Comuna": "Peñalolen",
  "id": "112",
  "Direccion": "Palena 1741",
  "Telefono": "+5622939 7790",
  "Email": "No Registra",
  "puntuación": "200",
  "Reseña": "Los sellos educativos del Colegio Likankura de Peñalolén, se fundamentan en la construcción de un colegio de calidad, hermanado en las familias y en las comunidades, respetuoso de la diversidad, y en donde se vivencie la inclusión y el respeto. Somos un colegio comprometido con el medio ambiente, la participación democrática y la alimentación saludable, la integración curricular de actividades artísticas, culturales y deportivas que contribuyan a la formación integral de nuestros estudiantes",
  "web": "https://www.cormup.cl/educacion/reduca/likankura/",
  "colegioStudent": true,
  "escuelaStaff": false,
  "alive": true,
  "image" :"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyOxkM41gPkPnf4km6ILfxA-biJrz79L57UlmEM0jT4262puc_Qw&s"

},
{
  "name": "Colegio Divina Gabriela",
  "Comuna": "Pedro Aguirre Cerda",
  "id": "113",
  "Direccion": "Vecinal 2800",
  "Telefono": "+5622517 0097",
  "Email": "colegiodivinagabriela@gmail.com",
  "puntuación": "200",
  "Reseña": "Desarrollar en nuestros estudiantes, habilidades que favorezcan su crecimiento personal a través de la entrega de una educación integral e inclusiva basada en la formación de competencias y centrada en la compresión lectora y la resolución de problemas.",
  "web": "https://divinagabriela.cl/",
  "colegioStudent": true,
  "escuelaStaff": false,
  "alive": true,
  "image" :"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmKGfVUdF7ANMLcxe3IuXt_YGl1YhUIHPl2aorqkISXp9WkSuMbA&s"

},
{
  "name": "Colegio Madre de la Divina Providencia",
  "Comuna": "Macul",
  "id": "114",
  "Direccion": "Los Plátanos 3245",
  "Telefono": "+5622272 6004",
  "Email": "mdp.direccion@colegiomdp.cl",
  "puntuación": "200",
  "Reseña": "El Colegio Divina Providencia proporciona a niñas, niños y jóvenes una educación de calidad a través de la formación integral que considera aspectos cognitivos, espirituales, valóricos, culturales, artísticos y deportivos, potenciando sus competencias para continuar su trayectoria educativa y proyecto de vida desde un enfoque de formación católica-pluralista, favoreciendo una cultura de altas expectativas para su vida personal y comunitaria.",
  "web": "https://colegiomdp.cl/",
  "colegioStudent": true,
  "escuelaStaff": false,
  "alive": true,
  "image" :"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRX8OGe9L_V7gyOvN8J04-vzhZQHv5JxPTu1a47t4BvGWMm-pt6&s"

},
{
  "name": "Liceo Teniente Dagoberto Godoy",
  "Comuna": "Lo Prado",
  "id": "115",
  "Direccion": "Isla Decepción 232",
  "Telefono": "+5622779 3123",
  "Email": "No Registra",
  "puntuación": "200",
  "Reseña": "Lograr educación preescolar y escolar de calidad que maximice oportunidades de aprender en un contexto valórico cristiano.",
  "web": "http://www.redcrecemos.cl/",
  "colegioStudent": true,
  "escuelaStaff": false,
  "alive": true,
  "image" :"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTK1i1b9oSHPVI3Q605ucPTkSZUqBQRn880svWZup_hsh8uWI1u&s"

},

{
  "name": "Colegio San Lucas",
  "Comuna": "Lo Espejo",
  "id": "116",
  "Direccion": "Pedro Lira 9195",
  "Telefono": "+5622854 3401",
  "Email": "secretaria@colegiosanlucas.com",
  "puntuación": "200",
  "Reseña": "Cada estudiante que ingresa a nuestro colegio, no es considerado como una persona integral debe desarrollar todas sus capacidades y dimensiones, en forma equilibrada y armónica, de modo que, integrando la fe, la vida, y la cultura, sea capaz de insertarse positivamente como un agente de cambio social.",
  "web": "http://www.colegiosanlucas.com/",
  "colegioStudent": true,
  "escuelaStaff": false,
  "alive": true,
  "image" :"http://estudiopalma.cl/upfiles/galerias/4b5e3efb4d406_IZQ-COL-12.jpg"

},

{
  "name": "Instituto Estados Americanos lo Barnechea",
  "Comuna": "Lo Barnechea",
  "id": "117",
  "Direccion": "Quinchamalí Ote 259",
  "Telefono": "+5622827 3730",
  "Email": "tclaro@lobarnechea.cl",
  "puntuación": "200",
  "Reseña": "El Instituto Estados Americanos es un establecimiento Científico-Humanista que ofrece cursos desde Pre-Kinder a IVº medio y que nació el año 2010 tras la fusión de los colegios Diego Aracena Aguilar y Estados Americanos. Tiene por objetivo entregar un aprendizaje de calidad y conducir a los alumnos a la educación superior.",
  "web": "https://www.lobarnechea.cl/educacion/instituto-estados-americanos/?parent=Colegios%20Municipales",
  "colegioStudent": true,
  "escuelaStaff": false,
  "alive": true,
  "image" :"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcpLYRM1SPLsT4m27RUve-zxyGeGq0ZNqpPShzHIX2NFN4yrQtcA&s"

},

{
  "name": "Liceo Juan Pablo II de las Condes",
  "Comuna": "Las Condes",
  "id": "118",
  "Direccion": "Tongoy 1380",
  "Telefono": "+56 2 2720 6000",
  "Email": "No Registra",
  "puntuación": "200",
  "Reseña": "El liceo Juan Pablo II es un establecimiento Científico-Humanista que ofrece cursos desde Pre-Kinder a IVº medio y que nació el año 2010 tras la fusión de los colegios Diego Aracena Aguilar y Estados Americanos. Tiene por objetivo entregar un aprendizaje de calidad y conducir a los alumnos a la educación superior.",
  "web": "https://www.corplascondes.cl/educacion-jpII.php",
  "colegioStudent": true,
  "escuelaStaff": false,
  "alive": true,
  "image" :"https://fastly.4sqi.net/img/general/200x200/S9HJUIs3PZJ2WIsphPAHcLqLQUEP_25AiC8PzKuKSMc.jpg"

},
{
  "name": "Colegio San Constantino",
  "Comuna": "La Reina",
  "id": "119",
  "Direccion": "Av. Larrain 9201",
  "Telefono": "+5622520 1354.",
  "Email": "col.sc@corp-lareina.cl",
  "puntuación": "200",
  "Reseña": "Asegurar para nuestros estudiantes un servicio educativo de calidad en forma responsable y constante, mediante un trabajo basado en la autonomía, creatividad, innovación, respetando las diferencias individuales e inspiradas en los principios de la cultura helénica.",
  "web": "http://semanaeducacionartistica.cultura.gob.cl/author/colegio-san-constantino/",
  "colegioStudent": true,
  "escuelaStaff": false,
  "alive": true,
  "image" :"https://pbs.twimg.com/media/DL9mtmrWkAcejfB.jpg"

},
{
  "name": "Colegio Christian Garden",
  "Comuna": "La Granja",
  "id": "120",
  "Direccion": "Sofia Eastman 10279",
  "Telefono": "+562541 1639",
  "Email": "No Registra",
  "puntuación": "200",
  "Reseña": "El colegio The Garden School entrega a sus estudiantes una formación integral, de forma que sus egresados sean portadores de un desarrollo afectivo, cognitivo e intelectual moderno y consistente respecto de las necesidades de su comunidad. Lo que les permitirá el acceso a estudios superiores de las más diversas índoles: universitarios, técnicos e incluso una inserción laboral óptima de acuerdo a los perfiles que necesita el mercado. Nuestro colegio cumple su MISIÓN elaborando y construyendo progresivamente un liderazgo institucional asentado en el mejoramiento sistemático de la calidad de la educación. Formar estudiantes que sean capaces de comprender la valoración social de los procesos culturales posmodernos, estudiantes críticos de su entorno social-mediático, estudiantes pensantes en un mundo cosmogónico, ideario y fértil a razón de su desarrollo afectivo.",
  "web": "https://gardenschool.cl/",
  "colegioStudent": true,
  "escuelaStaff": false,
  "alive": true,
  "image" :"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_m-ZdFR1cVXbhaBsSGi5_bV0LAIAe0RZJ5bHRGICZP7hDpPv4kw&s"

},
{
  "name": "Colegio Marista La Pintana - Marcelino Champagnat",
  "Comuna": "La Pintana",
  "id": "121",
  "Direccion": " VI de Línea 13540,",
  "Telefono": " +569 7855 1237",
  "Email": "colegio@cmch.maristas.cl",
  "puntuación": "200",
  "Reseña": "Somos un Colegio de Iglesia, que busca evangelizar educando a la comunidad, al estilo marista. Conocemos la realidad de sus alumnos y se preocupa por todos, con especial atención a los más necesitados. Formamos a niños y jóvenes, a través de una Educación Técnica de excelencia, para que, desarrollando sus propias capacidades y valores, se comprometan en la construcción de un mundo más solidario desde su propia vocación, y lleguen a ser Bueno cristianos y buenos ciudadanos",
  "web": "http://www.cmch.maristas.cl/",
  "colegioStudent": true,
  "escuelaStaff": false,
  "alive": true,
  "image" :"https://photos.wikimapia.org/p/00/06/06/01/19_full.jpg"

},
{
  "name": "Sociedad Educacional Peter College S.A.",
  "Comuna": "Cerrillo",
  "id": "122",
  "Direccion": "Sta Teresita 7558",
  "Telefono": "+562557 2286",
  "Email": "pcollege@petercollege.tie.cl",
  "puntuación": "200",
  "Reseña": "Entregar una educación de excelencia, bilingüe y de vanguardia, basada en valores judeo-cristianos y que se nutre de la diversidad cultural, para preparar personas íntegras que contribuyan activamente al desarrollo de la sociedad, en un mundo globalizado sujeto a un cambio continuo.",
  "web": "http://www.petercollege.com/",
  "colegioStudent": true,
  "escuelaStaff": false,
  "alive": true,
  "image" :"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRoIX2YS0KSiysccSq3D2KhiLSBJuTMb_rND_bH5q_LHWHiBhDtQ&s"

},
{
  "name": "Colegio Particular Isla Wellington",
  "Comuna": "La Florida",
  "id": "123",
  "Direccion": "Trinidad 1595",
  "Telefono": "+562262 8210",
  "Email": "colwellington@terra.cl",
  "puntuación": "200",
  "Reseña": "Proyectar una escuela en la que se desarrolle la Unidad Educativa en un ambiente grato y motivador para una sana convivencia escolar, a la implementación de un centro educativo que reúna las condiciones de infraestructura, recursos humanos, técnicos y materiales que permitan brindar una educación de calidad.",
  "web": "https://www.civico.com/lugar/colegio-isla-wellington-santiago/",
  "colegioStudent": true,
  "escuelaStaff": false,
  "alive": true,
  "image" :"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTu6xedl5FT5w_rwReS_bKjZHyULi72lGXx509N1-j2mX5ltjQW&s"

},
{
  "name": "Colegio San Damián",
  "Comuna": "Cerro Navia",
  "id": "124",
  "Direccion": "Doctor Sótero del Río 593",
  "Telefono": "+56 226942300",
  "Email": "direccion@colegiosandamian.cl",
  "puntuación": "200",
  "Reseña": "Nuestro colegio, como parte del proceso de reflexión, ha instaurado permanentemente los espacios necesarios para el análisis del quehacer pedagógico que origina la creación y actualización de nuestra misión y visión, relacionado con lo que aspiramos a ser, a entregar y a vivir en el actuar cotidiano de nuestra comunidad educativa.",
  "web": "https://colegiosandamian.cl/",
  "colegioStudent": true,
  "escuelaStaff": false,
  "alive": true,
  "image" :"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjf29ZeKYj-mgsTMyUGP7VKIpIDKMh_edU-xDaD0aoVV6KSaiDYA&s"

},
{
  "name": "Liceo Almirante Riveros",
  "Comuna": "Conchali",
  "id": "125",
  "Direccion": "Ernesto Ried 5730",
  "Telefono": "+562623 2223",
  "Email": "liceo.almiranteriveros@coresam.cl",
  "puntuación": "200",
  "Reseña": "Entregar a los estudiantes una formación integral, sólida y de calidad, desde nivel preescolar hasta 4° medio, acorde a los requerimientos del Ministerio de Educación, en el marco de una educación científico humanista con énfasis en las artes, integrando en el accionar del establecimiento a toda la comunidad educativa.",
  "web": "http://liceoalmiranteriveros.cl/",
  "colegioStudent": true,
  "escuelaStaff": false,
  "alive": true,
  "image" :"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqHoejwkANYhyb4ZdjJzO93E6T2M50syg3dyrYuh0GgW8IljCf&s"

},
{
  "name": "Colegio Particular José Abelardo Núñez",
  "Comuna": "El Bosque",
  "id": "126",
  "Direccion": " Los Avellanos 10721",
  "Telefono": "+5622558 3943",
  "Email": "No Registra",
  "puntuación": "200",
  "Reseña": "La Sociedad Educacional JAN es una institución educativa que se esfuerza por mejorar la calidad de la educación del país, a través de una red de 5 establecimientos que imparten educación desde el nivel preescolar a educación media Humanístico Científico. Nuestro objetivo es generar las condiciones para mejorar los aprendizajes de conocimientos, habilidades y actitudes esenciales para la participación plena en la sociedad del conocimiento. Asimismo, busca proporcionar oportunidades significativas a los estudiantes, favoreciendo la convivencia escolar en un marco de respeto, solidaridad y responsabilidad.",
  "web": "http://semanaeducacionartistica.cultura.gob.cl/author/colegio-particular-jose-abelardo-nunez-1/",
  "colegioStudent": true,
  "escuelaStaff": false,
  "alive": true,
  "image" :""

<<<<<<< HEAD
=======
},
{
  "name": "Colegio Echaurren",
  "Comuna": "Estacion Central",
  "id": "127",
  "Direccion": "Luis Infante Cerda 5484",
  "Telefono": "+5622741 3747",
  "Email": "No Registra",
  "puntuación": "200",
  "Reseña": "Ser una institución educativa que desarrolla al máximo las potencialidades de nuestros estudiantes, sustentada en la cosmovisión bíblica; asumiendo la vanguardia educativa en nuestra comuna",
  "web": "https://colegioechaurren.cl/",
  "colegioStudent": true,
  "escuelaStaff": false,
  "alive": true,
  "image" :"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROkwQ2fIiXNKaLGhT0XoysiNtXz3hp-6r8AByNQzimjR8Afa_y&s"

},
{
  "name": "Colegio Pumahue Huechuraba",
  "Comuna": "Huechuraba",
  "id": "128",
  "Direccion": "Av. Sta. Rosa de Huechuraba 7201",
  "Telefono": "+562 2605 9003",
  "Email": "consultachile@cognita.com",
  "puntuación": "200",
  "Reseña": "Formamos personas íntegras, desafiándolas a desarrollar su máximo potencial para que lideren su vida, contribuyendo positivamente en un mundo global y cambiante.",
  "web": "https://www.pumahue.cl/huechuraba/",
  "colegioStudent": true,
  "escuelaStaff": false,
  "alive": true,
  "image" :"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNYmgvyqqN4GO96GUP0dzXRSvGjj6HKgcGUkyWlarZICURPsGOgA&s"

},
{
  "name": "Liceo Rosa Ester Alessandri Rodríguez",
  "Comuna": "Independencia",
  "id": "129",
  "Direccion": "Huasco 1889",
  "Telefono": " +5622710 3066",
  "Email": " isescribano@rear.cl",
  "puntuación": "200",
  "Reseña": "Desarrollamos el  “El juego Justo” como filosofía de vida, promoviendo una alimentación adecuada y actividad física sistemática, en pos de un estilo de vida saludable. Incluyendo en el universo de la Unidad Educativa la Pasión por la acción con responsabilidad social.",
  "web": "https://www.independencia.cl/centros-educacionales/",
  "colegioStudent": true,
  "escuelaStaff": false,
  "alive": true,
  "image" :"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjc58pm3U-cOEPLIBAJ5Odw16RbhzbCBRNLP1zG_g62gDGON7U8g&s"

},
{
  "name": "Colegio Naciones Unidas",
  "Comuna": "La Cisterna",
  "id": "130",
  "Direccion": "Isabel La Católica 960",
  "Telefono": "+562558 6869",
  "Email": "n_unidas@cisterna.cl",
  "puntuación": "200",
  "Reseña": "Desarrollamos el  “El juego Justo” como filosofía de vida, promoviendo una alimentación adecuada y actividad física sistemática, en pos de un estilo de vida saludable. Incluyendo en el universo de la Unidad Educativa la Pasión por la acción con responsabilidad social.",
  "web": "https://www.escuelanacionesunidas.com/",
  "colegioStudent": true,
  "escuelaStaff": false,
  "alive": true,
  "image" :"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZJ4qD6OahsqdM_gqT9V5098HYFetgD9dXnFqgkXHOQjoZ8Drk_g&s"

>>>>>>> bd60843648577594628e61ec98fb593f0b3f0cad
}

];